config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: sec-fix/sqaas
      repo: https://github.com/ARGOeu/argo-messaging
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-ochre-dollar.sh
        container: qc.acc_whiny-violet-havanese
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-smalt-flounder.sh
        container: qc.doc_lousy-aquamarine-dog
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-fuchsia-frigatebird.sh
        container: qc.doc_skinny-tangerine-spaniel
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-olive-wombat.sh
        container: qc.doc_slaphappy-razzmatazz-sponge
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chocolate-capybara.sh
        container: qc.lic_skanky-wheat-whippet
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-violet-bloodhound.sh
        container: qc.met_gloppy-black-bear
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-silver-dog.sh
        container: qc.sec_tasty-chestnut-birman
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.randy-pumpkin-cattle.sh
        container: qc.sec_greasy-white-snail
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-chartreuse-bison.sh
        container: qc.sty_ready-harlequin-ant
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-ruby-liger.sh
        container: qc.sty_snoopy-bronze-dingo
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-ruby-warthog.sh
        container: qc.sty_sunny-gamboge-coyote
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-celadon-sheepdog.sh
        container: qc.ver_shaky-cornflower-bison
timeout: 5400
