config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-messaging:
      branch: devel
      repo: https://github.com/argoeu/argo-messaging
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-turquoise-oriole.sh
        container: qc.acc_grumpy-red-neanderthal
  QC.Doc:
    repos:
      github.com/argoeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-magnolia-binturong.sh
        container: qc.doc_cranky-beige-ragdoll
      github.com/argoeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-orange-hound.sh
        container: qc.doc_gamy-dandelion-cougar
      github.com/argoeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-teal-tang.sh
        container: qc.doc_woolly-platinum-bonobo
  QC.Lic:
    repos:
      github.com/argoeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-celadon-mouse.sh
        container: qc.lic_gloppy-olive-insect
  QC.Sec:
    repos:
      github.com/argoeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-plum-mandrill.sh
        container: qc.sec_squirrely-purple-albatross
      github.com/argoeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-azure-okapi.sh
        container: qc.sec_slaphappy-aquamarine-tzu
  QC.Sty:
    repos:
      github.com/argoeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-yellow-uakari.sh
        container: qc.sty_muzzy-azure-abyssinian
      github.com/argoeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-mustard-crane.sh
        container: qc.sty_nippy-yellow-buffalo
      github.com/argoeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-amethyst-shrimp.sh
        container: qc.sty_pasty-cerulean-wasp
  QC.Ver:
    repos:
      github.com/argoeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-beige-lobster.sh
        container: qc.ver_squeaky-apricot-cockroach
timeout: 5400
