config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/agelostsal/argo-messaging:
      branch: devel
      repo: https://github.com/agelostsal/argo-messaging
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/agelostsal/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-carmine-hippopotamus.sh
        container: qc.acc_dorky-cardinal-gibbon
  QC.Doc:
    repos:
      github.com/agelostsal/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-yellow-sheepdog.sh
        container: qc.doc_hasty-orange-ragdoll
      github.com/agelostsal/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-firebrick-caracal.sh
        container: qc.doc_skimpy-cinnamon-avocet
      github.com/agelostsal/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-rose-tamarin.sh
        container: qc.doc_pasty-zucchini-retriever
  QC.Lic:
    repos:
      github.com/agelostsal/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cream-bordeaux.sh
        container: qc.lic_seedy-wheat-mouse
  QC.Sec:
    repos:
      github.com/agelostsal/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-buff-bear.sh
        container: qc.sec_bumpy-scarlet-crane
      github.com/agelostsal/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-charcoal-camel.sh
        container: qc.sec_droopy-maroon-sparrow
  QC.Sty:
    repos:
      github.com/agelostsal/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-yellow-donkey.sh
        container: qc.sty_pokey-copper-urchin
      github.com/agelostsal/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-myrtle-goat.sh
        container: qc.sty_geeky-aquamarine-loon
      github.com/agelostsal/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cornflower-iguana.sh
        container: qc.sty_snappy-lilac-shark
  QC.Ver:
    repos:
      github.com/agelostsal/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-carmine-dormouse.sh
        container: qc.ver_messy-fuchsia-mongrel
timeout: 5400
