config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: master
      repo: https://github.com/ARGOeu/argo-messaging
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-buff-gibbon.sh
        container: qc.acc_randy-jade-falcon
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-chestnut-grasshopper.sh
        container: qc.doc_cheeky-aquamarine-quail
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-yellow-ragdoll.sh
        container: qc.doc_tacky-azure-hedgehog
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-asparagus-kudu.sh
        container: qc.doc_flimsy-cinnabar-mayfly
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-blue-markhor.sh
        container: qc.lic_dorky-magnolia-millipede
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-auburn-discus.sh
        container: qc.sec_crappy-pink-blue
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-persimmon-rhinoceros.sh
        container: qc.sec_flimsy-salmon-chimpanzee
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-pink-mammoth.sh
        container: qc.sty_hilly-malachite-salamander
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-buff-olm.sh
        container: qc.sty_sunny-cobalt-sparrow
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-ivory-rattlesnake.sh
        container: qc.sty_cranky-salmon-anteater
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-russet-fly.sh
        container: qc.ver_tacky-viridian-chipmunk
timeout: 5400
