config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: sec-fix/sqaas
      repo: https://github.com/ARGOeu/argo-messaging
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-mustard-hedgehog.sh
        container: qc.acc_cloudy-cinnabar-chihuahua
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cerulean-zebu.sh
        container: qc.doc_cheeky-flax-lynx
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-linen-hornet.sh
        container: qc.doc_craggy-denim-hare
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-cinnabar-olm.sh
        container: qc.doc_scaly-ochre-whale
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-auburn-lemming.sh
        container: qc.lic_flimsy-eggplant-rottweiler
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.silly-heliotrope-dingo.sh
        container: qc.met_lanky-saffron-dormouse
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-pumpkin-terrier.sh
        container: qc.sec_sunny-lemon-birman
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-bistre-termite.sh
        container: qc.sec_chewy-russet-hare
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-auburn-deer.sh
        container: qc.sty_chummy-pumpkin-kingfisher
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-red-bobcat.sh
        container: qc.sty_whiny-sepia-scorpion
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-tan-heron.sh
        container: qc.sty_cranky-periwinkle-havanese
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-alizarin-impala.sh
        container: qc.ver_clammy-violet-kangaroo
timeout: 5400
