config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-messaging:
      branch: devel
      repo: https://github.com/argoeu/argo-messaging
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-charcoal-oriole.sh
        container: qc.acc_nerdy-alizarin-bison
  QC.Doc:
    repos:
      github.com/argoeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-sangria-beaver.sh
        container: qc.doc_dorky-brown-moorhen
      github.com/argoeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-harlequin-reindeer.sh
        container: qc.doc_wheezy-pear-lemming
      github.com/argoeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-yellow-loon.sh
        container: qc.doc_woozy-buff-mule
  QC.Lic:
    repos:
      github.com/argoeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-blue-moorhen.sh
        container: qc.lic_slimy-persimmon-beaver
  QC.Sec:
    repos:
      github.com/argoeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-cornflower-slug.sh
        container: qc.sec_baggy-malachite-armadillo
      github.com/argoeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-magenta-cheetah.sh
        container: qc.sec_silly-rust-sheep
  QC.Sty:
    repos:
      github.com/argoeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-olive-monkey.sh
        container: qc.sty_gimpy-malachite-oriole
      github.com/argoeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-olivine-cow.sh
        container: qc.sty_frumpy-violet-okapi
      github.com/argoeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-asparagus-turkey.sh
        container: qc.sty_cloudy-maroon-boar
  QC.Ver:
    repos:
      github.com/argoeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-eggplant-chimpanzee.sh
        container: qc.ver_slimy-sepia-owl
timeout: 5400
