config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: devel
      repo: https://github.com/ARGOeu/argo-messaging
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-platinum-octopus.sh
        container: qc.acc_cranky-asparagus-bird
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cerulean-wolverine.sh
        container: qc.doc_sickly-celadon-mandrill
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-plum-pig.sh
        container: qc.doc_bumpy-magenta-wrasse
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-coral-angora.sh
        container: qc.doc_grumpy-lime-tapir
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cinnabar-tiger.sh
        container: qc.lic_woolly-black-tapir
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-charcoal-buzzard.sh
        container: qc.met_hazy-sepia-cougar
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-pumpkin-fousek.sh
        container: qc.sec_bluesy-black-worm
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.ready-wisteria-fousek.sh
        container: qc.sec_gummy-cornflower-alligator
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-purple-bat.sh
        container: qc.sty_bluesy-azure-turtle
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-brown-eagle.sh
        container: qc.sty_whiny-saffron-whale
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-burgundy-manatee.sh
        container: qc.sty_lumpy-silver-audemer
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cobalt-wolf.sh
        container: qc.ver_gummy-gold-boar
timeout: 5400
